<option data-state="" value="">-- YOUR CHURCH --</option>
<option data-state="ACT">Hội Thánh Tin Lành ACT (VECA) ACT</option>
<option data-state="NSW">Hội Thánh Anh Giáo Việt Nam Regents Park (Ang) NSW</option>
<option data-state="NSW">Hội Thánh Anh Giáo Việt Nam Villawood (Ang) NSW</option>
<option data-state="NSW">Hội Thánh Báp-tít Ân Điển Việt Nam Cabramatta (Bap) NSW </option>
<option data-state="NSW">Hội Thánh Cộng Đồng Nếp Sống Mới (Bap) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Báp-tít Hurlstone Park (Bap) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Bình An (Bap) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Quê Hương (CMA) NSW </option>
<option data-state="NSW">Hội Thánh Tin Lành Tình Thương Việt Nam (CMA) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việt Nam Kingsgrove (CMA) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việt Nam Tây Sydney (CMA) NSW</option>
<option data-state="NSW">Hội Thánh Cơ Đốc Truyền Giáo (IND) NSW</option>
<option data-state="NSW">Hội Thánh Hy Vọng (IND) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Nguồn Phước (IND) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việt Nam Bankstown (IND) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việ̣t Nam Fairfield (IND) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việ̣t Nam Punchbowl (IND) NSW</option>
<option data-state="NSW">Hội Thánh Lời Sự Sống (Pen) NSW</option>
<option data-state="NSW">Jesus Family Centre (Pent) NSW</option>
<option data-state="NSW">Croydon Park Uniting Church (UCA) NSW</option>
<option data-state="NSW">Hội Thánh Uniting Church VN Cabramatta (UCA) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việt Nam Cabramatta (VECA) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việt Nam Marrickville (VECA) NSW</option>
<option data-state="NSW">Hội Thánh Tin Lành Việt Nam Wollongong (VECA) NSW</option>
<option data-state="NZ">Hội Thánh Tin Lành Việt Nam Auckland (IND) NZ</option>
<option data-state="QLD">Hội Thánh Báp-tít Việt Anh Brisbane (Bap) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Ân Điển Việt Nam Brisbane (Bap) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Ân Điển Việt Nam Woodridge (Bap) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Báp-tít Ân Điển Rockhampton (Bap) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Việt Nam Brisbane (CMA) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Church of Christ Việt Nam (COC) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Gold Coast (IND) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Người Việt Queenland (IND) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Lutheran Á Châu (Lut) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Trưởng Lão Thánh Kinh (Pre) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Việt Nam (UCA) QLD</option>
<option data-state="QLD">Hội Thánh Tin Lành Việt Nam Brisbane (VECA) QLD</option>
<option data-state="SA">Woodville North Baptist Church (Bap) SA </option>
<option data-state="SA">Hội Thánh Tin Lành Việt Nam Adelaide (CMA) SA </option>
<option data-state="SA">Hội Thánh Tin Lành Salisbury (VECA) SA </option>
<option data-state="SA">Hội Thánh Tin Lành Việt Nam Nam Úc (VECA) SA </option>
<option data-state="VIC">Hội Thánh Ân Điển Melbourne (ACC) VIC</option>
<option data-state="VIC">Hội Thánh Full Gospel Assembly Melbourne (AOG) VIC</option>
<option data-state="VIC">Chi hội Báp-tít Người Hoa (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Báp-tít Sự Sống Mới Brimbank (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Báp-tít Kew (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Báp-tít Reservoir (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Báp-tít Sunshine (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Báp-tít Syndal (Bap) VIC</option>
<option data-state="VIC">Nhóm Tín Hữu Báp-tít New Hope (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Nguồn An Bình (Bap) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam Footscray (CMA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam Seddon (CMA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam Springvale Central (CMA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam St Albans (CMA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam Richmond (COC) VIC </option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam Springvale (COC) VIC </option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam Mitcham (UCA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Việt Nam West Footscray (UCA) VIC</option>
<option data-state="VIC">Nhóm Người Việt Tại Hội Thánh Tin Lành St Albans (UCA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Melbourne (VECA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Springvale (VECA) VIC</option>
<option data-state="VIC">Hội Thánh Tin Lành Tây Victoria (VECA) VIC</option>
<option data-state="VIC">Trung Tâm Truyền Giảng Springvale (VECA) VIC</option>
<option data-state="VIC">Trung Tâm Truyền Giảng Yarra (VECA) VIC</option>
<option data-state="WA">Hội Thánh Phúc Âm Toàn Vẹn Perth (AOG) WA </option>
<option data-state="WA">Hội Thánh Cơ Đốc Vĩnh Hằng (Bap) WA </option>
<option data-state="WA">Hội Thánh Tin Lành Việt Nam Perth (CMA) WA </option>
<option data-state="WA">Hội Thánh Tin Lành Việt Nam Perth (VECA) WA </option>
<option data-state="WA,TAS,QLD,VIC,SA,NT,NSW,ACT">Other</option>